### ISSUE TITLE
Date suffix issue

### ISSUE THREAD

**Issue by kneissl** [mskocik/svelty-picker#173]
with displayFormat="DD MM dS"
I'm seeing date with text: "Monday May 13rd"

**Comment by mskocik** [comment]
fixed now

**Comment by kneissl** [comment]
looks like you missed it on line 134 of src/lib/utils/dateUtils.js

**Comment by mskocik** [comment]
Somehow I forgot I added this option to `standard` format type as well 😆 fixed now
